/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcadormi;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author fermelli
 */
public class FormCliente extends javax.swing.JFrame {

    IAhorcado ahorcado;

    /**
     * Creates new form FormClient
     */
    public FormCliente() {
        initComponents();
        init();
        crearBotonesLetras();
        iniciarJuego();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        labelNumeroIntentos = new javax.swing.JLabel();
        labelPalabraOculta = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        labelNumeroIntentos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNumeroIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNumeroIntentos.setFocusable(false);
        labelNumeroIntentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelPalabraOculta.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelPalabraOculta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPalabraOculta.setFocusable(false);
        labelPalabraOculta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnReiniciar.setText("Reiniciar Juego");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNumeroIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelPalabraOculta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnReiniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNumeroIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        iniciarJuego();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    private void crearBotonesLetras() {
        int charCode = 65;
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 5; j++) {
                if (charCode <= 90) {
                    Character c = (char) charCode;
                    int y = 40 * i;
                    int x = 40 * j;
                    panelBotones.add(crearBoton(Character.toString(c), x, y));
                    charCode++;
                }
            }
        }
    }

    private void init() {
        try {
            ahorcado = (IAhorcado) Naming.lookup("rmi://localhost/Ahorcado");
        } catch (MalformedURLException | NotBoundException | RemoteException e) {
            System.out.println(e);
        }
    }

    private void iniciarJuego() {
        try {
            ahorcado.iniciar();
            labelPalabraOculta.setText(ahorcado.getPalabraOculta());
            labelNumeroIntentos.setText("Número de intentos: " + ahorcado.getNumeroIntentos());
            Component[] botones = panelBotones.getComponents();
            for (Component boton : botones) {
                boton.setEnabled(true);
            }
        } catch (RemoteException e) {
            System.out.println(e);
        }
    }

    private JButton crearBoton(String text, int x, int y) {
        JButton boton = new JButton();
        boton.setText(text);
        boton.setBounds(x, y, 40, 40);
        boton.setVisible(true);
        boton.addActionListener((ActionEvent e) -> {
            try {
                boton.setEnabled(false);
                if (ahorcado.intento(text.toLowerCase().charAt(0))) {
                    labelPalabraOculta.setText(ahorcado.getPalabraOculta());
                    if (ahorcado.esGanador()) {
                        JOptionPane.showMessageDialog(this, "¡Genial, ganaste el juego!");
                        iniciarJuego();
                    }
                } else {
                    int numeroIntentos = ahorcado.getNumeroIntentos();
                    labelNumeroIntentos.setText("Número de intentos: " + numeroIntentos);
                    if (numeroIntentos == 0) {
                        JOptionPane.showMessageDialog(this, "Ya no tiene intentos");
                        iniciarJuego();
                    }
                }
            } catch (RemoteException ex) {
                Logger.getLogger(FormCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        return boton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel labelNumeroIntentos;
    private javax.swing.JLabel labelPalabraOculta;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
