//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebServiceSegip.ServiceSegip {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSegip.WebServiceSegipSoap")]
    public interface WebServiceSegipSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteWebServiceSegip.ServiceSegip.Persona ObtenerDatos(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebServiceSegip.ServiceSegip.Persona> ObtenerDatosAsync(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComprobarDatos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteWebServiceSegip.ServiceSegip.Resultado ComprobarDatos(string Carnet, string Nombres, string PrimerApellido, string SegundoApellido, string FechaNacimiento, string Sexo, string EstadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComprobarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebServiceSegip.ServiceSegip.Resultado> ComprobarDatosAsync(string Carnet, string Nombres, string PrimerApellido, string SegundoApellido, string FechaNacimiento, string Sexo, string EstadoCivil);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombresField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string fechaNacimientoField;
        
        private string sexoField;
        
        private string estadoCivilField;
        
        private string carnetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("Nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("PrimerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("SegundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("FechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EstadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("EstadoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Carnet {
            get {
                return this.carnetField;
            }
            set {
                this.carnetField = value;
                this.RaisePropertyChanged("Carnet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Resultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool coincideNombresField;
        
        private bool coincidePrimerApellidoField;
        
        private bool coincideSegundoApellidoField;
        
        private bool coincideFechaNacimientoField;
        
        private bool coincideSexoField;
        
        private bool coincideEstadoCivilField;
        
        private bool coincideCarnetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool CoincideNombres {
            get {
                return this.coincideNombresField;
            }
            set {
                this.coincideNombresField = value;
                this.RaisePropertyChanged("CoincideNombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool CoincidePrimerApellido {
            get {
                return this.coincidePrimerApellidoField;
            }
            set {
                this.coincidePrimerApellidoField = value;
                this.RaisePropertyChanged("CoincidePrimerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool CoincideSegundoApellido {
            get {
                return this.coincideSegundoApellidoField;
            }
            set {
                this.coincideSegundoApellidoField = value;
                this.RaisePropertyChanged("CoincideSegundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool CoincideFechaNacimiento {
            get {
                return this.coincideFechaNacimientoField;
            }
            set {
                this.coincideFechaNacimientoField = value;
                this.RaisePropertyChanged("CoincideFechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool CoincideSexo {
            get {
                return this.coincideSexoField;
            }
            set {
                this.coincideSexoField = value;
                this.RaisePropertyChanged("CoincideSexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool CoincideEstadoCivil {
            get {
                return this.coincideEstadoCivilField;
            }
            set {
                this.coincideEstadoCivilField = value;
                this.RaisePropertyChanged("CoincideEstadoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CoincideCarnet {
            get {
                return this.coincideCarnetField;
            }
            set {
                this.coincideCarnetField = value;
                this.RaisePropertyChanged("CoincideCarnet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSegipSoapChannel : ClienteWebServiceSegip.ServiceSegip.WebServiceSegipSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSegipSoapClient : System.ServiceModel.ClientBase<ClienteWebServiceSegip.ServiceSegip.WebServiceSegipSoap>, ClienteWebServiceSegip.ServiceSegip.WebServiceSegipSoap {
        
        public WebServiceSegipSoapClient() {
        }
        
        public WebServiceSegipSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSegipSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSegipSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSegipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWebServiceSegip.ServiceSegip.Persona ObtenerDatos(string ci) {
            return base.Channel.ObtenerDatos(ci);
        }
        
        public System.Threading.Tasks.Task<ClienteWebServiceSegip.ServiceSegip.Persona> ObtenerDatosAsync(string ci) {
            return base.Channel.ObtenerDatosAsync(ci);
        }
        
        public ClienteWebServiceSegip.ServiceSegip.Resultado ComprobarDatos(string Carnet, string Nombres, string PrimerApellido, string SegundoApellido, string FechaNacimiento, string Sexo, string EstadoCivil) {
            return base.Channel.ComprobarDatos(Carnet, Nombres, PrimerApellido, SegundoApellido, FechaNacimiento, Sexo, EstadoCivil);
        }
        
        public System.Threading.Tasks.Task<ClienteWebServiceSegip.ServiceSegip.Resultado> ComprobarDatosAsync(string Carnet, string Nombres, string PrimerApellido, string SegundoApellido, string FechaNacimiento, string Sexo, string EstadoCivil) {
            return base.Channel.ComprobarDatosAsync(Carnet, Nombres, PrimerApellido, SegundoApellido, FechaNacimiento, Sexo, EstadoCivil);
        }
    }
}
